name: Build And Deploy Project

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: write

    steps: 
      - name: Create properties file from secrets
        run: |
          echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./application.properties
          echo "${{ secrets.CONFIG_PROPERTIES }}" > ./config.properties
