name: Build And Deploy Project

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps: 
      - name: Create properties file from secrets
        run: |
          echo "${{ secrets.APPLICATION_PROPERTIES }}"
          echo "${{ secrets.CONFIG_PROPERTIES }}"
